apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${APP_NAME}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '5'
    spec:
      containerConcurrency: 50
      containers:
        - image: ${IMAGE}
          resources:
            limits:
              cpu: 1
              memory: 256M
          ports:
            - containerPort: ${PORT}
          timeoutSeconds: 60

  traffic:
    - percent: 100
      latestRevision: true
