name: Build & Deploy

on:
  push:
    branches:
      - main
      - ci-test/**
    # paths:
    #   - 'apps/api/**'
    #   - 'packages/**'

  workflow_dispatch:
    inputs:
      app_version:
        description: App version
        required: true

env:
  CONTAINER_REGISTRY_NAME: europe-west2-docker.pkg.dev
  GCP_PROJECT_ID: template-455111
  ARTIFACT_REPO: gcr-template
  APP_NAME: api
  REGION: europe-west2

jobs:
  build-tag-push:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - name: Registry Auth
        id: docker-auth
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: '${{ steps.auth.outputs.access_token }}'
          registry: ${{ env.CONTAINER_REGISTRY_NAME }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/api/Dockerfile
          target: final
          build-args: |
            SHA=${{ inputs.github_ref }}
            VERSION=${{ inputs.app_version }}
          push: true
          tags: ${{ env.CONTAINER_REGISTRY_NAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.APP_NAME }}:${{ github.sha }}

      - name: GCP Cloud Run Service
        run: |
          export IMAGE="${{ env.CONTAINER_REGISTRY_NAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.APP_NAME }}:${{ github.sha }}"
          export APP_NAME="${{ env.APP_NAME }}"
          export PROJECT_ID="${{ env.GCP_PROJECT_ID }}"
          export REVISION_TAG="${{ github.sha }}"
          export CLOUD_RUN_SA="${{ secrets.GCP_SERVICE_ACCOUNT }}"
          export ENVIRONMENT="production"
          envsubst < ./apps/api/config/gcp-cloud-run-service.template.yaml > container-production.yaml
          cat container-production.yaml

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          name: ${{ env.APP_NAME }}
          region: ${{ env.REGION }}
          metadata: container-production.yaml
