name: Build & Deploy

on:
  push:
    branches:
      - main
      - ci-test/**
    # paths:
    #   - 'apps/api/**'
    #   - 'packages/**'

  workflow_dispatch:
    inputs:
      app_version:
        description: App version
        required: true

env:
  CONTAINER_REGISTRY_NAME: europe-west2-docker.pkg.dev

jobs:
  build-push:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - name: Registry Auth
        id: docker-auth
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: '${{ steps.auth.outputs.access_token }}'
          registry: ${{ env.CONTAINER_REGISTRY_NAME }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/api/Dockerfile
          target: final
          build-args: |
            SHA=${{ inputs.github_ref }}
            VERSION=${{ inputs.app_version }}
          push: true
          tags: ${{ env.CONTAINER_REGISTRY_NAME }}/template-455111/gcr-template/api:${{ github.sha }}
