name: Build & Deploy

on:
  push:
    branches:
      - main
      - ci-test/**
    # paths:
    #   - 'apps/api/**'
    #   - 'packages/**'

  workflow_dispatch:
    inputs:
      app_version:
        description: App version
        required: true

jobs:
  build-push:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          project_id: template
          workload_identity_provider: projects/675933940278/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: github-actions@template-455111.iam.gserviceaccount.com

      - name: Registry Auth
        id: docker-auth
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: '${{ steps.auth.outputs.access_token }}'
          registry: europe-west2-docker.pkg.dev

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/api/Dockerfile
          target: final
          build-args: |
            SHA=${{ inputs.github_ref }}
            VERSION=${{ inputs.app_version }}
          push: true
          tags: europe-west2-docker.pkg.dev/template-455111/gcr-template:${{ github.sha }}
